name: "Lesson 2 - Exercise 4"

on:
          push:
            branches:
              - main
              # Match the release branches of the format: releases/1, releases/2, etc.
              - "releases/[0-9]"

# Add your solution below this line
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true


jobs:
          release:
            strategy:
              matrix:
                version: ['0.1.0','0.1.1']
            runs-on: ${{ matrix.version }}
            steps:
              - name: Build and release
                run: |
                  echo "Building branch: ${{ github.ref }} for version: ${{ matrix.version }}"
                  sleep 10
